### ISSUE TITLE
Ability to turn off GA ping when offline

### ISSUE THREAD

**Issue by jhaynie** [iopipe/iopipe-js#23]
Trying to work offline locally (no internet connection ... caltrain), i couldn't hit my functions because Google Analytics dns lookup fails.  

I tried setting `iopipeNoStats` in serverless.yaml but there seems to be a code issue (i ended up just removing iopipe temporary to work).

Easy to reproduce by turning off your Internet connection and run with serverless offline.

**Comment by pselle** [comment]
Thank you for the report! This impacts users of the serverless plugin, so I've opened an issue over there (where we can fix it): https://github.com/iopipe/serverless-plugin-iopipe/issues/85.
