### ISSUE TITLE
NodeJS support for Lambda Layers

### ISSUE THREAD

**Issue by ewindisch** [iopipe/iopipe-js#44]
Lambda layers: ```Lambda can't find the file @iopipe/iopipe.js```

A readme section was added describing how to manually integrate IOpipe to resolve this error, but we need to be able to integrate w/o code modifications.

I think this used to work... I'm not sure what changed, but we can no longer import the @iopipe/iopipe module as a handler directly.

**Comment by kolanos** [comment]
@ewindisch Unfortunately the fix is that the Node.js runtime needs to perform a `require.resolve` against the `NODE_PATH`. This is functionally how the Python runtime works, where the runtime bootstrap sets the `sys.path`. I have no idea why the Node.js runtime isn't doing something similar.

**Comment by ewindisch** [comment]
This is not currently supported by AWS.

We will be switching to using a custom provider in the short-term:
https://github.com/iopipe/iopipe-cli/issues/19

**Comment by ewindisch** [comment]
This issue should remain open until there is native support in the AWS runtimes.

The existing code works with custom runtimes. We will need to update documentation for layers as part of this, or another, issue.

https://github.com/iopipe/iopipe-cli will not be blocked by use of custom runtimes.

**Comment by kolanos** [comment]
This is an issue with the runtime itself.
